---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eksworkshop-eksctl
  region: $AWS_REGION
  version: "1.21"

availabilityZones: ["$AZ0", "$AZ1", "$AZ2"]

managedNodeGroups:
- name: eksworkshop-eksctl-ng
  desiredCapacity: 1
  minSize: 1
  maxSize: 10
  amiFamily: AmazonLinux2
  instanceType: m5.large
  ssh:
    enableSsm: true

iam:
  withOIDC: true
