---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eksworkshop-eksctl
  region: $AWS_REGION

managedNodeGroups:
- name: eksworkshop-eksctl-ng
  desiredCapacity: 1
  minSize: 1
  maxSize: 10
  amiFamily: AmazonLinux2
  instanceType: t3.medium
  ssh:
    enableSsm: true