# NOTE: Bottlerocket AMI might not be available in all regions.
# Please check AWS official doc or below link for more details
# https://github.com/bottlerocket-os/bottlerocket/blob/develop/QUICKSTART.md#finding-an-ami
# A simple example of ClusterConfig object with Bottlerocket settings:
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eksworkshop-eksctl
  region: $AWS_REGION

nodeGroups:
  - name: eksworkshop-eksctl-ng-bottlerocket
    instanceType: m5.large
    desiredCapacity: 2
    amiFamily: Bottlerocket
    ami: auto-ssm
    labels:
      "bottlerocket": "true"
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
    bottlerocket:
      enableAdminContainer: true
      settings:
        motd: "Hello, eksctl!"
