apiVersion: v1
kind: Service
metadata:
  name: multiarch-service
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
  labels:
    app: multiarch-app
spec:
  selector:
    app: multiarch-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer